Perf changes
specklesystems/speckle-sharp-sdk pull request #79
Opened 2024-08-15 11:32 UTC by adamhathcock

2024-08-15 12:00 UTC, JR-Morgan requested changes

2024-08-15 12:03 UTC, adamhathcock commented on src/Speckle.Sdk/Serialisation/SerializationUtilities/BaseObjectSerializationUtilities.cs
> -        ret[prop.Name.ToLower()] = prop;
ToLower always makes a new string...we should never use it!

2024-08-15 12:06 UTC, adamhathcock commented on src/Speckle.Sdk/Serialisation/SerializationUtilities/ValueConverter.cs
> +  private static object[] _singleValue = new object[1];
I'm making a static array that I'm going to reuse instead of making a new one

2024-08-15 12:07 UTC, adamhathcock commented on src/Speckle.Sdk/Serialisation/SerializationUtilities/BaseObjectSerializationUtilities.cs
> +      return  ret ?? [..Array.Empty<MethodInfo>()];
not really because it wants a list.  I'm forcing an empty list with a shared array so it won't allocate one inside the list.

2024-08-15 12:07 UTC, adamhathcock commented on src/Speckle.Sdk/Serialisation/SerializationUtilities/BaseObjectSerializationUtilities.cs
> +          .GetCustomAttribute<OnDeserializedAttribute>(true);
cool, I'll use that

2024-08-15 13:43 UTC, adamhathcock commented
Using JsonReader for closures reduces allocations:
![image](https://github.com/user-attachments/assets/988deeab-607b-4526-a545-13612e2b40bf)
to
![Screenshot 2024-08-15 143437](https://github.com/user-attachments/assets/6a606af1-66ee-4f3e-9bf4-75e6635e020b)

2024-08-15 13:47 UTC, JR-Morgan commented on src/Speckle.Sdk/Serialisation/SerializationUtilities/BaseObjectSerializationUtilities.cs
> +      return  ret ?? [..Array.Empty<MethodInfo>()];
It wants an IReadOnlyList... which an array is no?

2024-08-15 13:58 UTC, JR-Morgan commented on src/Speckle.Sdk/Serialisation/SerializationUtilities/BaseObjectSerializationUtilities.cs
> -        ret[prop.Name.ToLower()] = prop;
Ah ok, I missed the `StringComparer.OrdinalIgnoreCase`

2024-08-15 14:00 UTC, JR-Morgan commented on src/Speckle.Sdk/Serialisation/SerializationUtilities/ValueConverter.cs
> +  private static object[] _singleValue = new object[1];
Ah ok, for the params! ok this makes sense
A comment would be good because its a little hidden

2024-08-19 11:05 UTC, JR-Morgan approved these changes

2024-08-19 11:05 UTC, merged