Json reader deserialize
specklesystems/speckle-sharp-sdk pull request #88
Opened 2024-08-20 11:14 UTC by adamhathcock

2024-09-02 15:34 UTC, JR-Morgan requested changes

2024-09-03 09:31 UTC, JR-Morgan requested changes

2024-09-03 12:06 UTC, adamhathcock commented on src/Speckle.Sdk/Serialisation/BaseObjectDeserializerV2.cs
> -        //but adding throw here breaks blobs tests, see CNX-8541
I'm not sure.....looks like the issue wants to throw an exception.  Right now I'm returning null.  What should I do?

2024-09-03 12:10 UTC, adamhathcock commented on tests/Speckle.Sdk.Tests.Unit/Serialisation/SerializerNonBreakingChanges.cs
> +  /*
I did this when doing some Task stuff...fixed now

2024-09-03 14:32 UTC, JR-Morgan approved these changes

2024-09-03 14:53 UTC, JR-Morgan approved these changes

2024-09-03 14:53 UTC, merged

2024-09-03 16:02 UTC, JR-Morgan commented
| Method  | Mean    | Error   | StdDev  | Gen0          | Gen1        | Gen2      | Allocated |
|-------- |--------:|--------:|--------:|--------------:|------------:|----------:|----------:|
| RunTest | 31.28 s | 1.491 s | 0.986 s |  637000.0000  | 260000.0000 | 2000.0000 |  11.10 GB |
| RunTest | 20.66 s | 0.293 s | 0.194 s | 1548000.0000  | 553000.0000 | 1000.0000 |  24.84 GB |